### ISSUE TITLE
Missing Candles

### ISSUE THREAD

**Issue by snehil2010** [abinthomasonline/findata#4]
I see several missing candles in the data. 

See below image as an example. The file is \findata-master\BANKNIFTY\options\2021-06-10\30000PE.csv

![image](https://user-images.githubusercontent.com/63507577/124393022-bca71a00-dcf8-11eb-8809-d92747808cba.png)

**Comment by ashwanthkumar** [comment]
Options are generally active only on the expiry week and not before that, especially weekly options. That's probably why they're missing from here, it would have been nice to have them pre-filled using the last known values though.

**Comment by ashwanthkumar** [comment]
@abinthomasonline Would you be willing to accept PRs with such fixes?

**Comment by abinthomasonline** [comment]
@ashwanthkumar No. 
Forward filling will explode the size of the data given the number of illiquid options traded.

**Comment by abinthomasonline** [comment]
You can check in a macro to do this filling though! 🙂

**Comment by alphaQ314** [comment]
@abinthomasonline Thank you for helping us with all this data. Do you plan on posting for June, July months and in the foreseeable future?
